# Usa PHP-FPM
FROM php:8.2-fpm

# Extensões mínimas
RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www/html
COPY . .

# Exemplo de composer (caso precise)
# COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
# RUN composer install --no-dev --optimize-autoloader

# Expõe a porta padrão do PHP-FPM (Render detecta)
EXPOSE 9000

CMD ["php-fpm"]
